Briefs = {
	"SWE": {
	"Software Engineer": "As Software Engineer you are involved with the entire development lifecycle, thus you analyse, design, propose, develop, test, configure, deploy, operate, troubleshoot, maintain, and improve multiple software products, services, pipelines and tools, and related components – which together compose an essential part of the service portfolio CSCS offers to the scientific community. You perform activities aimed at ensuring high quality and performant implementations and adherence to standards within the teams of work you are part of. You participate into planning and review activities. You collaborate with internal and external colleagues, scientists, and other stakeholders for the definition of the necessary architectures and roadmaps, for the necessary implementations and well as to communicate results.",
	"Data Engineer": "As Data Engineer you analyse, design, propose, model, develop, test, configure, deploy, operate, troubleshoot, maintain, and improve multiple data products, services, tools, ETL pipelines, and related components that are used to store, process, and analyse data – which together support the service portfolio that CSCS offers to the scientific community. You perform activities aimed at ensuring high quality and performant implementations and adherence to standards within your teams. You participate into planning and review activities. You collaborate with internal and external colleagues, scientists, and other stakeholders for the definition of the necessary architectures and roadmaps, for the necessary implementations and well as to communicate results.",
	"IAM Architect": "As IAM Architect you analyse, design, propose, develop, test, configure, deploy, operate, troubleshoot, maintain, and improve identity and access solutions, as well as related components and policies – which together are required to effectively serve the service portfolio that CSCS offers to the scientific community, as well as to facilitate the collaboration with partners. More broadly, you develop and maintain the vision and roadmap in the IAM field, in accordance with the current direction of the Centre.",
	"IT Security Analyst": "As IT Security Analyst you analyse, design, propose, develop, test, configure, deploy, operate, troubleshoot, maintain, and improve security related measures, components, services, monitoring, and tools aimed at protecting CSCS from cyber threats – which together reduce the likelihood of security alerts, incidents, and disasters – which would impact the scientific community served by CSCS. You handle security incidents, lead the end-to-end post-mortem processes, and write reports on adopted responses. You provide insights on the efficacy of the current security policies, controls and disaster recovery plans, and other security-related information.",
	"Information Security Officer": "As Information Security Officer you analyse, design, propose, establish, monitor, and maintain policies, procedures, and related measures – which together reduce the likelihood of to confidentiality, integrity, and availability incidents that would impact the scientific community served by CSCS. You educate employees about information security risks and best practices, as well as for improving compliance with policies and procedures. You conduct risk assessments to identify and mitigate potential vulnerabilities. In the event of a major security incident or if an important security topic arises, you are the interface between the management and the technical areas.",
	"Research Project Manager": "As Research Project Manager you plan, coordinate, and manage the research projects in which CSCS participates and involving internal and external stakeholders. You develop and monitor goals, plans, timelines, and costs for the fulfillment of commitments undertaken by CSCS. You contribute to the securing of fundings for the projects and you monitor that the resources available are allocated and effectively employed. You coordinate the required reporting production and communicate progress and results accordingly."
	},
    "RE" : {
    "Research Software Engineer": "As Research Software Engineer you collaborate with domain scientists to develop scientific applications and libraries able to leverage the most advanced supercomputers in the world, following best software engineering practices. As Research Software Engineer you are involved with the entire development lifecycle, thus you analyse, design, propose, develop, test, configure, deploy, operate, troubleshoot, maintain, and improve multiple software products, services, pipelines and tools, and related components – which together compose an essential part of the service portfolio CSCS offers to the scientific community. You perform activities aimed at ensuring high quality and performant implementations and adherence to standards within the teams of work you are part of. You participate into planning and review activities, collaborating with internal and external colleagues, scientists, and other stakeholders for the necessary implementations and well as to communicate results."
	},
	"SE": {
	"System Engineer": "As Systems Engineer you design, develop, deploy and operate a cutting edge HPC datacentre infrastructure in collaboration with industry leaders to support scientific research."
	},
	"HE": {
	"HPC Engineer": "As HPC Application Engineer you interface between CSCS' cutting-edge datacentre infrastructure and our HPC users. You will design, develop, test, configure, deploy and maintain the HPC user environment and engage with scientists, providing support and consultancy to enable them to make best use of our research infrastructure You perform activities aimed at ensuring high quality and performant implementations and adherence to standards within the teams of work you are part of. You participate into planning and review activities, collaborating with  colleagues, scientists, and other stakeholders for the necessary implementations and well as to communicate results."
	}
}

Roles = {
	6: {
	"SWE": {
	"1": ["You assist the set-up, development, and integration of selected software solutions in a well-defined context, and where applicable their automated deployment, testing, monitoring, backup, and similar operational aspects, in the DevOps spirit and following established procedures given by the lead.", "55"],
	"2": ["You participate to the end-to-end support of software products, and their deployments, according to the predetermined support level. Thus, you interact with end users and follow-up to ensure requirements are met, and to develop improvements to services.", "20"],
	"3": ["As part of small and possibly ephemeral groups of work, you collaborate into solving demanding problems. Such groups are characterised by common backgrounds, interests, and points of view.", "5"],
	"4": ["", ""],
	"5": ["You communicate on demanding or sensitive contents, that you are mostly familiar with, to a homogeneous audience. You document your solutions and implementations, and proactively present the results of your work to the teams you collaborate with.", "5"],
	"6": ["You assist to the definition and delivery of trainings, workshops, and similar activities, as defined by the internal stakeholders (es. WS lead, Service Managers, Unit Head, others\).", "5"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might self-study or participate to trainings, conferences, workshops and similar. You share relevant the new knowledge acquired with colleagues in a structured way.", "10"]
	},
	"RE": {
	"1": ["You assist the development of selected software components, libraries and/or applications in a well-defined context, and where applicable their automated build, deployment, testing, and similar operational aspects, in the DevOps spirit and following established procedures given by the lead.", "80"],
	"2": ["You participate to the end-to-end support of software components, libraries and applications and their deployments, according to the predetermined support level. Thus, you interact with end users and follow-up to ensure requirements are met, and to develop improvements to services. ", "10"],
	"3": ["As part of small and possibly ephemeral groups of work, you collaborate into solving demanding problems. Such groups are characterised by common backgrounds, interests, and points of view.", "5"],
	"4": ["", ""],
	"5": ["You communicate on demanding or sensitive contents, that you are mostly familiar with, to a homogeneous audience. You document your solutions and implementations, and proactively present the results of your work to the teams you collaborate with.", "5"],
	"6": ["You assist to the definition and delivery of trainings, workshops, and similar activities, as defined by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "5"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might self-study or participate to trainings, conferences, workshops and similar. You share relevant the new knowledge acquired with colleagues in a structured way.", "10"]
	},
	"SE": {
	"1": ["You assist the installation and operation of assigned systems and services in a well-defined context, and where applicable their automated deployment, monitoring, backup, and similar operational aspects, in the DevOps spirit and following established procedures given by the lead.", "75"],
	"2": ["You participate to the end-to-end support of operational services, and their deployments, according to the predetermined support level. Thus, you interact with end users and follow-up to ensure requirements are met, and to develop improvements to services.", "0"],
	"3": ["As part of small and possibly ephemeral groups of work, you collaborate into solving demanding problems. Such groups are characterised by common backgrounds, interests, and points of view.", "5"],
	"4": ["", ""],
	"5": ["You communicate on demanding or sensitive contents, that you are mostly familiar with, to a homogeneous audience. You document your solutions and implementations, and proactively present the results of your work to the teams you collaborate with.", "5"],
	"6": ["You assist to the definition and delivery of trainings, workshops, and similar activities, as defined by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "5"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might self-study or participate to trainings, conferences, workshops and similar. You share relevant the new knowledge acquired with colleagues in a structured way.", "10"]
	},
	"HE": {	
	"1": ["You assist the set-up and development of HPC-focused services targeted to specific scientific domains, in a well-defined context, and where applicable their automated build, deployment, testing, and similar operational aspects, in the DevOps spirit and following established procedures given by the lead", "50"],
	"2": ["You participate to the end-to-end support of HPC services, and their deployments, according to the predetermined support level. Thus, you interact with end users and follow-up to ensure requirements are met, and to develop improvements to services. ", "10"],
	"3": ["As part of small and possibly ephemeral groups of work, you collaborate into solving demanding problems. Such groups are characterised by common backgrounds, interests, and points of view.", "5"],
	"4": ["", ""],
	"5": ["You communicate on demanding or sensitive contents, that you are mostly familiar with, to a homogeneous audience. You document your solutions and implementations, and proactively present the results of your work to the teams you collaborate with.", "5"],
	"6": ["You assist to the definition and delivery of trainings, workshops, and similar activities, as defined by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "5"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might self-study or participate to trainings, conferences, workshops and similar. You share relevant the new knowledge acquired with colleagues in a structured way.", "10"]
}
	},
	7: { 
	"SWE": {	
	"1": ["You independently contribute to the development, test, deployment, and operation, of multiple integrations and software solutions in the DevOps spirit and following established procedures as agreed with the lead. This includes the proposal, evaluation, and introduction of new technologies. You contribute to the quality of the implementation and appropriate documentation, also proposing the adoption of methods and processes improvements.", "70"],
	"2": ["You independently contribute to the end-to-end support of software products, and their deployments, according to the predetermined support level. Thus, you interact with end users and follow-up to ensure requirements are met, and to develop improvements to services. You also engage with end users to understand their workflows and needs.", "20"],
	"3": ["As part of a small and possibly ephemeral groups of work, you collaborate into solving complex problems, such as analysing a problem to the root cause resolution, or regarding the design of entirely new solution. Such groups are characterised by different backgrounds, interests, and points of view.", "5"],
	"4": ["", ""],
	"5": ["You communicate on demanding or sensitive topics, that you might not be familiar with, to a mostly homogeneous audience which includes recipients outside of your multi-disciplinary group of work and with aligned backgrounds and interests. You document your solutions and implementations, and proactively present the results of your work to the teams you collaborate with. On request, you contribute to the production of posters, papers and other contributions for external events  \(e.g. conferences, workshops \)", "5"],
	"6": ["You contribute to the definition and delivery of trainings, workshops, and similar activities, as described by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "6"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might self-study or participate to trainings, conferences, workshops and similar. You share relevant the new knowledge acquired with colleagues in a structured way.", "10"]
	},
	"RE": {	
	"1": ["You independently contribute to the development, test, deployment, and operation, of multiple software components, libraries and/or applications in the DevOps spirit and following established procedures as agreed with the lead. This includes the proposal, evaluation, and introduction of new technologies. You contribute to the quality of the implementation and appropriate documentation, also proposing the adoption of methods and processes improvements.", "70"],
	"2": ["You independently contribute to the end-to-end support of software components, libraries and applications and their deployments, according to the predetermined support level. Thus, you interact with end users and follow-up to ensure requirements are met, and to develop improvements to services. You also engage with end users to understand their workflows and needs.", "10"],
	"3": ["As part of a small and possibly ephemeral groups of work, you collaborate into solving complex problems, such as analysing a problem to the root cause resolution, or regarding the design of entirely new solution. Such groups are characterised by different backgrounds, interests, and points of view.", "5"],
	"4": ["", ""],
	"5": ["You communicate on demanding or sensitive topics, that you might not be familiar with, to a mostly homogeneous audience which includes recipients outside of your multi-disciplinary group of work and with aligned backgrounds and interests. You document your solutions and implementations, and proactively present the results of your work to the teams you collaborate with. On request, you contribute to the production of posters, papers and other contributions for external events  \(e.g. conferences, workshops\). Support the interaction with PhD students, PostDocs, users, and partners.", "5"],
	"6": ["You contribute to the definition and delivery of trainings, workshops, and similar activities, as described by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "6"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might self-study or participate to trainings, conferences, workshops and similar. You share relevant the new knowledge acquired with colleagues in a structured way.", "10"]
	},
	"SE": {	
	"1": ["You independently contribute to the development, installation, and operation of multiple systems and services in the DevOps spirit and following established procedures as agreed with the lead. This includes the proposal, evaluation, and introduction of new technologies. You contribute to the quality of the implementation, appropriate documentation, also proposing the adoption of methods and processes improvements.", "70"],
	"2": ["You independently contribute to the end-to-end support of operational services, and their deployments, according to the predetermined support level. Thus, you interact with end users and follow-up to ensure requirements are met, and to develop improvements to services. You also engage with end users to understand their workflows and needs.", "10"],
	"3": ["As part of a small and possibly ephemeral groups of work, you collaborate into solving complex problems, such as analysing a problem to the root cause resolution, or regarding the design of entirely new solution. Such groups are characterised by different backgrounds, interests, and points of view.", "5"],
	"4": ["", ""],
	"5": ["You communicate on demanding or sensitive topics, that you might not be familiar with, to a mostly homogeneous audience which includes recipients outside of your multi-disciplinary group of work and with aligned backgrounds and interests. You document your solutions and implementations, and proactively present the results of your work to the teams you collaborate with. On request, you contribute to the production of posters, papers and other contributions for external events  \(e.g. conferences, workshops \)", "5"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might self-study or participate to trainings, conferences, workshops and similar. You share relevant the new knowledge acquired with colleagues in a structured way.", "10"]
	},
	"HE": {	
	"1": ["You independently contribute to the analyse, plan, develop and set-up HPC-focused targeted to specific scientific domains in the DevOps spirit and following established procedures as agreed with the lead. This includes the development of tools necessary to support automated deployment, testing and benchmarking. You contribute to the quality of the implementation and appropriate documentation, also proposing the adoption of methods and processes improvements.", "70"],
	"2": ["You independently contribute to the end-to-end support of HPC services, and their deployments, according to the predetermined support level. Thus, you interact with end users and follow-up to ensure requirements are met, and to develop improvements to services. You also engage with end users to understand their workflows and needs.", "20"],
	"3": ["As part of a small and possibly ephemeral groups of work, you collaborate into solving complex problems, such as analysing a problem to the root cause resolution, or regarding the design of entirely new solution. Such groups are characterised by different backgrounds, interests, and points of view.", "5"],
	"4": ["", ""],
	"5": ["You communicate on demanding or sensitive topics, that you might not be familiar with, to a mostly homogeneous audience which includes recipients outside of your multi-disciplinary group of work and with aligned backgrounds and interests. You document your solutions and implementations, and proactively present the results of your work to the teams you collaborate with. On request, you contribute to the production of posters, papers and other contributions for external events  \(e.g. conferences, workshops \). Support the interaction with PhD students, PostDocs, users, and partners.", "5"],
	"6": ["You contribute to the definition and delivery of trainings, workshops, and similar activities, as described by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "6"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might self-study or participate to trainings, conferences, workshops and similar. You share relevant the new knowledge acquired with colleagues in a structured way.", "10"]
	}
	},
	8: { 
	"SWE": {
	"1": ["You are responsible for gathering the requirements, design, develop and release multiple demanding software components, services, tools and related to internal and external customers following an end-to-end process as described by the lead and in line with the Centre-wide architectural choices. You apply your knowledge of technology and vendor roadmaps to contribute to the implementation, operation and maintenance of software components, services, and tools. You ensure the quality of the implementation and appropriate documentation, also proposing the adoption of methods and processes improvements.", "50"],
	"2": ["As an internally recognised expert in the field, you leverage your deep knowledge to lead the end-to-end support of software related products and services, and their deployments, according to the predetermined support level. Thus, you interact with end users and follow-up to ensure requirements are met, and to develop improvements to services. You also engage with end users to understand their workflows and needs.", "15"],
	"3": ["You closely assist or act as project managers and/or product owners as part of one or multiple projects in which our Centre is involved. In such groups you lead the collaboration required to solve complex problems. Such groups of work are characterised by different backgrounds, possibly conflicting interests, and points of view. You individually lead and mentor multi-disciplinary teams, possibly encompassing external collaborators, in a context of complex and changing requirements. You coordinate the resources entrusted to you in effective ways, proactively keeping a strong awareness of the overall context of which, your activities are part of. You follow-up with clients and local teams to ensure requirements are met, and to develop improvements to services. You contribute to activities meant to enable and support the business of the Centre  \(e.g. procurement, budgeting, hiring \).", "10"],
	"4": ["You mentor and proactively support colleagues in their work. Within your domains of specialisation, you strive to keep your knowledge up to date, which you proactively share in a structured way. You identify and propose measures to improve the way you and your teams perform the work, for example through new or improved operational procedures, conventions, methods of work, as well as adopting industry established standards.", "5"],
	"5": ["You communicate on demanding or sensitive topics, that you might not be familiar with, to a heterogeneous audience which includes recipients outside of your multi-disciplinary group of work, and with different backgrounds and interests. You take the initiative to present the results of your work to the Centre. Document your implementation and solutions. You take the initiative and produce posters, papers and other contributions for external events  \(e.g. conferences, workshops \). You contribute to discussions with PIs, researchers, external vendors and partners.", "5"],
	"6": ["You are responsible to propose, define and deliver trainings, workshops, and similar activities, as outlined by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "5"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might participate to trainings, conferences, workshops, self-study. You share relevant the new knowledge acquired with colleagues in a structured way.", "10"]
	},
	"RE": {	
	"1": ["You are responsible for gathering the requirements, design, implement multiple demanding software components, libraries and/or applications and to deliver them to external stakeholders following an end-to-end process as described by the lead and in line with the Centre-wide architectural choices. You apply your knowledge of technology and vendor roadmaps to contribute to the creation and implementation of new management tools and utilities and Software Defined Infrastructure workflows. You ensure the quality of the implementation and appropriate documentation, also proposing the adoption of methods and processes improvements.", "50"],
	"2": ["As an internally recognised expert in the field, you leverage your deep knowledge to lead the end-to-end support of software components, libraries and applications and their deployments, according to the predetermined support level. Thus, you interact with end users and follow-up to ensure requirements are met, and to develop improvements to services. You also engage with end users to understand their workflows and needs.", "15"],
	"3": ["You closely assist or act as project managers and/or product owners as part of one or multiple projects in which our Centre is involved. In such groups you lead the collaboration required to solve complex problems. Such groups of work are characterised by different backgrounds, possibly conflicting interests, and points of view. You individually lead and mentor multi-disciplinary teams, possibly encompassing external collaborators, in a context of complex and changing requirements. You coordinate the resources entrusted to you in effective ways, proactively keeping a strong awareness of the overall context of which, your activities are part of. You follow-up with clients and local teams to ensure requirements are met, and to develop improvements to services. You contribute to activities meant to enable and support the business of the Centre \(e.g. procurement, budgeting, hiring \).", "10"],
	"4": ["You mentor and proactively support colleagues in their work. Within your domains of specialisation, you strive to keep your knowledge up to date, which you proactively share in a structured way. You identify and propose measures to improve the way you and your teams perform the work, for example through new or improved operational procedures, conventions, methods of work, as well as adopting industry established standards.", "5"],
	"5": ["You communicate on demanding or sensitive topics, that you might not be familiar with, to a heterogeneous audience which includes recipients outside of your multi-disciplinary group of work, and with different backgrounds and interests. You take the initiative to present the results of your work to the Centre. Document your implementation and solutions. You take the initiative and produce posters, papers and other contributions for external events  \(e.g. conferences, workshops \). You contribute to discussions with PIs, researchers, external vendors and partners.", "5"],
	"6": ["You are responsible to propose, define and deliver trainings, workshops, and similar activities, as outlined by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "5"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might participate to trainings, conferences, workshops, self-study. You share relevant the new knowledge acquired with colleagues in a structured way.", "10"]
	},
	"SE": {	
	"1": ["You are responsible for gathering the requirements, design, development, installation, and operation of multiple demanding systems and services following an end-to-end process as described by the lead and in line with the Centre-wide architectural choices. You apply your knowledge of technology and vendor roadmaps to contribute to the creation and implementation of new management tools and utilities and Software Defined Infrastructure workflows. You ensure the quality of the implementation and appropriate documentation, also proposing the adoption of methods and processes improvements.", "60"],
	"2": ["As an internally recognised expert in the field, you leverage your deep knowledge to lead the end-to-end support of operational services, and their deployments, according to the predetermined support level. Thus, you interact with end users and follow-up to ensure requirements are met, and to develop improvements to services. You also engage with end users to understand their workflows and needs.", "10"],
	"3": ["You closely assist or act as project managers and/or product owners as part of one or multiple projects in which our Centre is involved. In such groups you lead the collaboration required to solve complex problems. Such groups of work are characterised by different backgrounds, possibly conflicting interests, and points of view. You individually lead and mentor multi-disciplinary teams, possibly encompassing external collaborators, in a context of complex and changing requirements. You coordinate the resources entrusted to you in effective ways, proactively keeping a strong awareness of the overall context of which, your activities are part of. You follow-up with clients and local teams to ensure requirements are met, and to develop improvements to services. You contribute to activities meant to enable and support the business of the Centre  \(e.g. procurement, budgeting, hiring \).", "10"],
	"4": ["You mentor and proactively support colleagues in their work. Within your domains of specialisation, you strive to keep your knowledge up to date, which you proactively share in a structured way. You identify and propose measures to improve the way you and your teams perform the work, for example through new or improved operational procedures, conventions, methods of work, as well as adopting industry established standards.", "5"],
	"5": ["You communicate on demanding or sensitive topics, that you might not be familiar with, to a heterogeneous audience which includes recipients outside of your multi-disciplinary group of work, and with different backgrounds and interests. You take the initiative to present the results of your work to the Centre. Document your implementation and solutions. You take the initiative and produce posters, papers and other contributions for external events  \(e.g. conferences, workshops \). You contribute to discussions with PIs, researchers, external vendors and partners.", "5"],
	"6": ["You are responsible to propose, define and deliver trainings, workshops, and similar activities, as outlined by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "5"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might participate to trainings, conferences, workshops, self-study. You share relevant the new knowledge acquired with colleagues in a structured way.", "10"]
	},
	"HE": {	
	"1": ["You are responsible for gather requirements, analyse, plan, develop and set-up multiple demanding HPC-focused services targeted to specific scientific domains following an end-to-end process as described by the lead and in line with the Centre-wide architectural choices. You apply your knowledge of technology and vendor roadmaps to contribute to the creation and implementation of new management tools and utilities and Software Defined Infrastructure workflows. You ensure the quality of the implementation and appropriate documentation, also proposing the adoption of methods and processes improvements.", "50"],
	"2": ["As an internally recognised expert in the field, you leverage your deep knowledge to lead the end-to-end support of HPC services, and their deployments, according to the predetermined support level. Thus, you interact with end users and follow-up to ensure requirements are met, and to develop improvements to services. You also engage with end users to understand their workflows and needs.", "15"],
	"3": ["You closely assist or act as project managers and/or product owners as part of one or multiple projects in which our Centre is involved. In such groups you lead the collaboration required to solve complex problems. Such groups of work are characterised by different backgrounds, possibly conflicting interests, and points of view. You individually lead and mentor multi-disciplinary teams, possibly encompassing external collaborators, in a context of complex and changing requirements. You coordinate the resources entrusted to you in effective ways, proactively keeping a strong awareness of the overall context of which, your activities are part of. You follow-up with clients and local teams to ensure requirements are met, and to develop improvements to services. You contribute to activities meant to enable and support the business of the Centre  \(e.g. procurement, budgeting, hiring \).", "10"],
	"4": ["You mentor and proactively support colleagues in their work. Within your domains of specialisation, you strive to keep your knowledge up to date, which you proactively share in a structured way. You identify and propose measures to improve the way you and your teams perform the work, for example through new or improved operational procedures, conventions, methods of work, as well as adopting industry established standards.", "5"],
	"5": ["You communicate on demanding or sensitive topics, that you might not be familiar with, to a heterogeneous audience which includes recipients outside of your multi-disciplinary group of work, and with different backgrounds and interests. You take the initiative to present the results of your work to the Centre. Document your implementation and solutions. You take the initiative and produce posters, papers and other contributions for external events  \(e.g. conferences, workshops \). You contribute to discussions with PIs, researchers, external vendors and partners.", "5"],
	"6": ["You are responsible to propose, define and deliver trainings, workshops, and similar activities, as outlined by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "5"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might participate to trainings, conferences, workshops, self-study. You share relevant the new knowledge acquired with colleagues in a structured way.", "10"]
	}
	},
	9: { 
	"SWE": {	
	"1": ["You lead the development of overall architectures of complex software solutions based on internal and external sparse or high-level functional requirements. You are responsible for the definition of the end-to-end process for your colleagues, ensuring alignment with the Centre-wide architectural choices. You leverage your network of contacts and apply your knowledge of technology and vendor roadmaps to contribute to the Centre-wide architectural roadmap. You monitor the quality of the implementation and appropriate documentation. You introduce and monitor the adoption of methods, standards, and processes at team level.", "45"],
	"2": ["As an internally recognised expert, you leverage your deep knowledge to lead the end-to-end support in multiple areas. With your deep knowledge of the underlying components, you assume the lead role in a team, paying particular attention to the dissemination of your key knowledge to other members. Thus, you support and interact with end users and follow-up to ensure requirements are met, and to develop improvements to services. You also engage with end to understand their workflows and needs.", "15"],
	"3": ["You act as project manager and/or product owner as part of multiple multi-institution or mission-critical projects in which our Centre is involved. You individually take ownership of the success of the project or product development, despite the difficulties posed e.g. by a context of complex and changing requirements. In such groups you individually lead the collaboration required to solve complex problems. Such groups of work are characterised by a medium to large participation, representing different backgrounds, possibly conflicting interests, points of view and including external collaborators from partner institutions. You coordinate the resources entrusted to you in effective ways, proactively keeping a strong awareness of the overall context of which, your activities are part of. You follow-up with clients and local teams to ensure requirements are met; and you lead continuous improvement efforts. You contribute or lead to activities meant to enable and support the business of the Centre  \(e.g. procurement, budgeting, hiring \).", "10"],
	"4": ["You develop and execute mentorship plans for more junior colleagues. Similarly, you engage with colleagues to understand their difficulties at work, and you proactively support them. Within your domains of specialisation, you strive to keep your knowledge up to date, which you proactively share in a structured way. You identify and propose measures to improve the way you and your teams perform the work, for example through new or improved operational procedures, conventions, methods of work, as well as adopting industry established standards.", "10"],
	"5": ["You communicate on complex and sensitive topics, that you might not be familiar with, to a heterogeneous audience representing different backgrounds and conflicting interests. In coordination with your lead, you take the initiative to present internally and externally the vision of the Centre in own field of activity and expertise. Take leadership in the documentation process for a given implementation or solution. You mentor colleagues in the production of posters, papers and other contributions for external events  \(e.g. conferences, workshops \). You moderate to discussions with PIs, researchers, external vendors, and partners.", "5"],
	"6": ["You are responsible to propose, define and deliver trainings, workshops, and similar activities, as outlined by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "10"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might participate to trainings, conferences, workshops, self-study. You share relevant the new knowledge acquired with colleagues in a structured way. You suggest and contribute to similar actions on the organizational level. Thus, you develop a plan for the development of the organization and actively follow its executions. You expand your knowledge of the relevant technologies, vendors, and partner institutions, thus developing a network of key contacts.", "10"]
	},
	"RE": {	
	"1": ["You lead the development of overall architectures of complex software products based on internal and external sparse or high-level functional requirements. You are responsible for the definition of the end-to-end process for your colleagues, ensuring alignment with the Centre-wide architectural choices. You leverage your network of contacts and apply your knowledge of technology and vendor roadmaps to contribute to the Centre-wide architectural roadmap. You monitor the quality of the implementation and appropriate documentation. You introduce and monitor the adoption of methods, standards, and processes at team level.", "40"],
	"2": ["As an internally recognised expert, you leverage your deep knowledge to lead the end-to-end support in multiple areas. With your deep knowledge of the underlying components, you assume the lead role in a team, paying particular attention to the dissemination of your key knowledge to other members. Thus, you support and interact with end users and follow-up to ensure requirements are met, and to develop improvements to services. You also engage with end to understand their workflows and needs.", "15"],
	"3": ["You act as project manager and/or product owner as part of multiple multi-institution or mission-critical projects in which our Centre is involved. You individually take ownership of the success of the project or product development, despite the difficulties posed e.g. by a context of complex and changing requirements. In such groups you individually lead the collaboration required to solve complex problems. Such groups of work are characterised by a medium to large participation, representing different backgrounds, possibly conflicting interests, points of view and including external collaborators from partner institutions. You coordinate the resources entrusted to you in effective ways, proactively keeping a strong awareness of the overall context of which, your activities are part of. You follow-up with clients and local teams to ensure requirements are met; and you lead continuous improvement efforts. You contribute or lead to activities meant to enable and support the business of the Centre  \(e.g. procurement, budgeting, hiring \).", "10"],
	"4": ["You develop and execute mentorship plans for more junior colleagues. Similarly, you engage with colleagues to understand their difficulties at work, and you proactively support them. Within your domains of specialisation, you strive to keep your knowledge up to date, which you proactively share in a structured way. You identify and propose measures to improve the way you and your teams perform the work, for example through new or improved operational procedures, conventions, methods of work, as well as adopting industry established standards.", "10"],
	"5": ["You communicate on complex and sensitive topics, that you might not be familiar with, to a heterogeneous audience representing different backgrounds and conflicting interests. In coordination with your lead, you take the initiative to present internally and externally the vision of the Centre in own field of activity and expertise. Take leadership in the documentation process for a given implementation or solution. You mentor colleagues in the production of posters, papers and other contributions for external events  \(e.g. conferences, workshops \). You moderate to discussions with PIs, researchers, external vendors, and partners.", "5"],
	"6": ["You are responsible to propose, define and deliver trainings, workshops, and similar activities, as outlined by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "10"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might participate to trainings, conferences, workshops, self-study. You share relevant the new knowledge acquired with colleagues in a structured way. You suggest and contribute to similar actions on the organizational level. Thus, you develop a plan for the development of the organization and actively follow its executions. You expand your knowledge of the relevant technologies, vendors, and partner institutions, thus developing a network of key contacts.", "10"]
	},
	"SE": {	
	"1": ["You lead the development of overall architectures of complex system solutions based on internal and external sparse or high-level functional requirements. You are responsible for the definition of the end-to-end process for your colleagues, ensuring alignment with the Centre-wide architectural choices. You leverage your network of contacts and apply your knowledge of technology and vendor roadmaps to contribute to the Centre-wide architectural roadmap. You monitor the quality of the implementation and appropriate documentation. You introduce and monitor the adoption of methods, standards, and processes at team level.", "50"],
	"2": ["As an internally recognised expert, you leverage your deep knowledge to lead the end-to-end support in multiple areas. With your deep knowledge of the underlying components, you assume the lead role in a team, paying particular attention to the dissemination of your key knowledge to other members. Thus, you support and interact with end users and follow-up to ensure requirements are met, and to develop improvements to services. You also engage with end to understand their workflows and needs.", "15"],
	"3": ["You act as project manager and/or product owner as part of multiple multi-institution or mission-critical projects in which our Centre is involved. You individually take ownership of the success of the project or product development, despite the difficulties posed e.g. by a context of complex and changing requirements. In such groups you individually lead the collaboration required to solve complex problems. Such groups of work are characterised by a medium to large participation, representing different backgrounds, possibly conflicting interests, points of view and including external collaborators from partner institutions. You coordinate the resources entrusted to you in effective ways, proactively keeping a strong awareness of the overall context of which, your activities are part of. You follow-up with clients and local teams to ensure requirements are met; and you lead continuous improvement efforts. You contribute or lead to activities meant to enable and support the business of the Centre  \(e.g. procurement, budgeting, hiring \).", "10"],
	"4": ["You develop and execute mentorship plans for more junior colleagues. Similarly, you engage with colleagues to understand their difficulties at work, and you proactively support them. Within your domains of specialisation, you strive to keep your knowledge up to date, which you proactively share in a structured way. You identify and propose measures to improve the way you and your teams perform the work, for example through new or improved operational procedures, conventions, methods of work, as well as adopting industry established standards.", "10"],
	"5": ["You communicate on complex and sensitive topics, that you might not be familiar with, to a heterogeneous audience representing different backgrounds and conflicting interests. In coordination with your lead, you take the initiative to present internally and externally the vision of the Centre in own field of activity and expertise. Take leadership in the documentation process for a given implementation or solution. You mentor colleagues in the production of posters, papers and other contributions for external events  \(e.g. conferences, workshops \). You moderate to discussions with PIs, researchers, external vendors, and partners.", "5"],
	"6": ["You are responsible to propose, define and deliver trainings, workshops, and similar activities, as outlined by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "10"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might participate to trainings, conferences, workshops, self-study. You share relevant the new knowledge acquired with colleagues in a structured way. You suggest and contribute to similar actions on the organizational level. Thus, you develop a plan for the development of the organization and actively follow its executions. You expand your knowledge of the relevant technologies, vendors, and partner institutions, thus developing a network of key contacts.", "10"]
	},
	"HE": {	
	"1": ["You lead the development of overall architectures of complex HPC-focused services targeted to scientific users based on internal and external sparse or high-level functional requirements. You are responsible for the definition of the end-to-end process for your colleagues, ensuring alignment with the Centre-wide architectural choices. You leverage your network of contacts and apply your knowledge of technology and vendor roadmaps to contribute to the Centre-wide architectural roadmap. You monitor the quality of the implementation and appropriate documentation. You introduce and monitor the adoption of methods, standards, and processes at team level.", "45"],
	"2": ["As an internally recognised expert, you leverage your deep knowledge to lead the end-to-end support in multiple areas. With your deep knowledge of the underlying components, you assume the lead role in a team, paying particular attention to the dissemination of your key knowledge to other members. Thus, you support and interact with end users and follow-up to ensure requirements are met, and to develop improvements to services. You also engage with end to understand their workflows and needs.", "15"],
	"3": ["You act as project manager and/or product owner as part of multiple multi-institution or mission-critical projects in which our Centre is involved. You individually take ownership of the success of the project or product development, despite the difficulties posed e.g. by a context of complex and changing requirements. In such groups you individually lead the collaboration required to solve complex problems. Such groups of work are characterised by a medium to large participation, representing different backgrounds, possibly conflicting interests, points of view and including external collaborators from partner institutions. You coordinate the resources entrusted to you in effective ways, proactively keeping a strong awareness of the overall context of which, your activities are part of. You follow-up with clients and local teams to ensure requirements are met; and you lead continuous improvement efforts. You contribute or lead to activities meant to enable and support the business of the Centre  \(e.g. procurement, budgeting, hiring \).", "10"],
	"4": ["You develop and execute mentorship plans for more junior colleagues. Similarly, you engage with colleagues to understand their difficulties at work, and you proactively support them. Within your domains of specialisation, you strive to keep your knowledge up to date, which you proactively share in a structured way. You identify and propose measures to improve the way you and your teams perform the work, for example through new or improved operational procedures, conventions, methods of work, as well as adopting industry established standards.", "10"],
	"5": ["You communicate on complex and sensitive topics, that you might not be familiar with, to a heterogeneous audience representing different backgrounds and conflicting interests. In coordination with your lead, you take the initiative to present internally and externally the vision of the Centre in own field of activity and expertise. Take leadership in the documentation process for a given implementation or solution. You mentor colleagues in the production of posters, papers and other contributions for external events  \(e.g. conferences, workshops \). You moderate to discussions with PIs, researchers, external vendors, and partners.", "5"],
	"6": ["You are responsible to propose, define and deliver trainings, workshops, and similar activities, as outlined by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "10"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might participate to trainings, conferences, workshops, self-study. You share relevant the new knowledge acquired with colleagues in a structured way. You suggest and contribute to similar actions on the organizational level. Thus, you develop a plan for the development of the organization and actively follow its executions. You expand your knowledge of the relevant technologies, vendors, and partner institutions, thus developing a network of key contacts.", "10"]
	}
	},
	10: { 
	"SWE": {	
	"1": ["As an externally recognized expert in the field, you have the broad understanding of internal and external  \(e.g. vendor \) plans related to technology roadmaps on which our complex HPC infrastructure depends. Thus, you lead the proposal, investigation, evaluation, development, and introduction of new future-oriented technologies to support the Centre’s strategy and advance its position in the industry. For complex software solutions with possibly unclear or contradictory goals, you take the leading role in the gathering of requirements, the coordination of stakeholders, the solution design, and implementation execution. You define the appropriate methods, standards, and processes needed at Centre level.", "40"],
	"2": ["As an externally recognised expert in your field, you take the lead in the establishment of standards, procedures, and roadmaps across the Centre and for international communities. As a contributor to the Centre overall strategy, you contribute to the long-term overall support effort associated with our services, ensuring general applicability across multiple entities. You have a network of contacts among our existing and prospective customers; thus, you bring insight with your contributions to support organization. You employ your deep technical knowledge to grow your colleagues through coaching, dissemination, and mentoring. You support and interact with end users and follow-up to ensure requirements are met, and to develop improvements to services.", "15"],
	"3": ["You are individually responsible for the definition, coordination, and success of a set of multi-institution or mission-critical projects in which our Centre is involved. You individually take ownership of the success of the project or product development, despite the difficulties posed e.g. by a context of complex and changing requirements. In such groups you individually lead the collaboration required to solve complex problems. Such groups of work are characterised by a medium to large participation, representing different backgrounds, possibly conflicting interests, points of view and including external collaborators from partner institutions. You coordinate the resources entrusted to you in effective ways, proactively keeping a strong awareness of the overall context of which, your activities are part of, and that you, as senior engineer contributes to shape. You follow-up with clients and local teams to ensure requirements are met; and you lead continuous improvement efforts. You contribute or lead to activities meant to enable and support the business of the Centre  \(e.g. procurement, budgeting, hiring \).", "10"],
	"4": ["You develop and execute mentorship plans for more junior colleagues. Similarly, you engage with colleagues to understand their difficulties at work, and you proactively support them. Within your domains of specialisation, you strive to keep your knowledge up to date, which you proactively share in a structured way. You identify and propose measures to improve the way you and your teams perform the work, for example through new or improved operational procedures, conventions, methods of work, as well as adopting industry established standards.", "10"],
	"5": ["You communicate on complex and sensitive topics, that you might not be familiar with, to a heterogeneous audience representing different backgrounds and conflicting interests. In coordination with your lead, you take the initiative to present internally and externally the vision of the Centre in own field of activity and expertise. Take leadership in the documentation process for a given implementation or solution. You mentor colleagues in the production of posters, papers and other contributions for external events  \(e.g. conferences, workshops \). You moderate to discussions with PIs, researchers, external vendors, and partners.", "10"],
	"6": ["You are responsible to propose, define and deliver trainings, workshops, and similar activities, as outlined by the internal stakeholders  \(es. WS lead, Service Managers, Unit Head, others\).", "5"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might participate to trainings, conferences, workshops, self-study. You share relevant the new knowledge acquired with colleagues in a structured way. You suggest and contribute to similar actions on the organizational level. Thus, you develop a plan for the development of the organization and actively follow its executions. You expand your knowledge of the relevant technologies, vendors, and partner institutions, thus developing a network of key contacts.", "10"]
    },
	"RE": {	
	"1": ["As an externally recognized expert in the field, you have the broad understanding of internal and external  \(e.g. vendor \) plans related to technology roadmaps on which our complex HPC infrastructure depends.  Thus, you lead the proposal, investigation, evaluation, development, and introduction of new future-oriented technologies to support the Centre’s strategy and advance its position in the industry. For complex high-performance libraries, software, or applications with possibly unclear or contradictory goals, you take the leading role in the gathering of requirements, the coordination of stakeholders, the solution design, and implementation execution. You define the appropriate methods, standards, and processes needed at Centre level.", "30"],
	"2": ["As an externally recognised expert in your field, you take the lead in the establishment of standards, procedures, and roadmaps across the Centre and for international communities. As a contributor to the Centre overall strategy, you contribute to the long-term overall support effort associated with our services, ensuring general applicability across multiple entities. You have a network of contacts among our existing and prospective customers; thus, you bring insight with your contributions to support organization. You employ your deep technical knowledge to grow your colleagues through coaching, dissemination, and mentoring. You support and interact with end users and follow-up to ensure requirements are met, and to develop improvements to services.", "15"],
	"3": ["You are individually responsible for the definition, coordination, and success of a set of multi-institution or mission-critical projects in which our Centre is involved. You individually take ownership of the success of the project or product development, despite the difficulties posed e.g. by a context of complex and changing requirements. In such groups you individually lead the collaboration required to solve complex problems. Such groups of work are characterised by a medium to large participation, representing different backgrounds, possibly conflicting interests, points of view and including external collaborators from partner institutions. You coordinate the resources entrusted to you in effective ways, proactively keeping a strong awareness of the overall context of which, your activities are part of, and that you, as senior engineer contributes to shape. You follow-up with clients and local teams to ensure requirements are met; and you lead continuous improvement efforts. You contribute or lead to activities meant to enable and support the business of the Centre  \(e.g. procurement, budgeting, hiring \).", "10"],
	"4": ["You develop and execute mentorship plans for more junior colleagues. Similarly, you engage with colleagues to understand their difficulties at work, and you proactively support them. Within your domains of specialisation, you strive to keep your knowledge up to date, which you proactively share in a structured way. You identify and propose measures to improve the way you and your teams perform the work, for example through new or improved operational procedures, conventions, methods of work, as well as adopting industry established standards.", "10"],
	"5": ["You communicate on complex and sensitive topics, that you might not be familiar with, to a heterogeneous audience representing different backgrounds and conflicting interests. In coordination with your lead, you take the initiative to present internally and externally the vision of the Centre in own field of activity and expertise. Take leadership in the documentation process for a given implementation or solution. You mentor colleagues in the production of posters, papers and other contributions for external events  \(e.g. conferences, workshops \). You moderate to discussions with PIs, researchers, external vendors, and partners.", "10"],
	"6": ["You are responsible to propose, define and deliver trainings, workshops, and similar activities, as outlined by the internal stakeholders (es. WS lead, Service Managers, Unit Head, others\).", "5"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might participate to trainings, conferences, workshops, self-study. You share relevant the new knowledge acquired with colleagues in a structured way. You suggest and contribute to similar actions on the organizational level. Thus, you develop a plan for the development of the organization and actively follow its executions. You expand your knowledge of the relevant technologies, vendors, and partner institutions, thus developing a network of key contacts.", "10"]
	},
	"SE": {	
	"1": ["As an externally recognized expert in the field, you have the broad understanding of internal and external (e.g. vendor \) plans related to technology roadmaps on which our complex HPC infrastructure depends. Thus, you lead the proposal, investigation, evaluation, development, and introduction of new future-oriented technologies to support the Centre’s strategy and advance its position in the industry. For complex infrastructure projects with possibly unclear or contradictory goals, you take the leading role in the gathering of requirements, the coordination of stakeholders, the solution design, and implementation execution. You define the appropriate methods, standards, and processes needed at Centre level.", "35"],
	"2": ["As an externally recognised expert in your field, you take the lead in the establishment of standards, procedures, and roadmaps across the Centre and for international communities. As a contributor to the Centre overall strategy, you contribute to the long-term overall support effort associated with our services, ensuring general applicability across multiple entities. You have a network of contacts among our existing and prospective customers; thus, you bring insight with your contributions to support organization. You employ your deep technical knowledge to grow your colleagues through coaching, dissemination, and mentoring. You support and interact with end users and follow-up to ensure requirements are met, and to develop improvements to services.", "15"],
	"3": ["You are individually responsible for the definition, coordination, and success of a set of multi-institution or mission-critical projects in which our Centre is involved. You individually take ownership of the success of the project or product development, despite the difficulties posed e.g. by a context of complex and changing requirements. In such groups you individually lead the collaboration required to solve complex problems. Such groups of work are characterised by a medium to large participation, representing different backgrounds, possibly conflicting interests, points of view and including external collaborators from partner institutions. You coordinate the resources entrusted to you in effective ways, proactively keeping a strong awareness of the overall context of which, your activities are part of, and that you, as senior engineer contributes to shape. You follow-up with clients and local teams to ensure requirements are met; and you lead continuous improvement efforts. You contribute or lead to activities meant to enable and support the business of the Centre  \(e.g. procurement, budgeting, hiring \).", "10"],
	"4": ["You develop and execute mentorship plans for more junior colleagues. Similarly, you engage with colleagues to understand their difficulties at work, and you proactively support them. Within your domains of specialisation, you strive to keep your knowledge up to date, which you proactively share in a structured way. You identify and propose measures to improve the way you and your teams perform the work, for example through new or improved operational procedures, conventions, methods of work, as well as adopting industry established standards.", "10"],
	"5": ["You communicate on complex and sensitive topics, that you might not be familiar with, to a heterogeneous audience representing different backgrounds and conflicting interests. In coordination with your lead, you take the initiative to present internally and externally the vision of the Centre in own field of activity and expertise. Take leadership in the documentation process for a given implementation or solution. You mentor colleagues in the production of posters, papers and other contributions for external events  \(e.g. conferences, workshops \). You moderate to discussions with PIs, researchers, external vendors, and partners.", "10"],
	"6": ["You are responsible to propose, define and deliver trainings, workshops, and similar activities, as outlined by the internal stakeholders \(es. WS lead, Service Managers, Unit Head, others\).", "5"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might participate to trainings, conferences, workshops, self-study. You share relevant the new knowledge acquired with colleagues in a structured way. You suggest and contribute to similar actions on the organizational level. Thus, you develop a plan for the development of the organization and actively follow its executions. You expand your knowledge of the relevant technologies, vendors, and partner institutions, thus developing a network of key contacts.", "10"]
	},
	"HE": {	
	"1": ["As an externally recognized expert in the field, you have the broad understanding of internal and external (e.g. vendor \) plans related to technology roadmaps on which our complex HPC infrastructure depends.  Thus, you lead the proposal, investigation, evaluation, development, and introduction of new future-oriented technologies to support the Centre’s strategy and advance its position in the industry. For complex HPC oriented services with possibly unclear or contradictory goals, you take the leading role in the gathering of requirements, the coordination of stakeholders, the solution design, and implementation execution. You define the appropriate methods, standards, and processes needed at Centre level.", "30"],
	"2": ["As an externally recognised expert in your field, you take the lead in the establishment of standards, procedures, and roadmaps across the Centre and for international communities. As a contributor to the Centre overall strategy, you contribute to the long-term overall support effort associated with our services, ensuring general applicability across multiple entities. You have a network of contacts among our existing and prospective customers; thus, you bring insight with your contributions to support organization. You employ your deep technical knowledge to grow your colleagues through coaching, dissemination, and mentoring. You support and interact with end users and follow-up to ensure requirements are met, and to develop improvements to services.", "15"],
	"3": ["You are individually responsible for the definition, coordination, and success of a set of multi-institution or mission-critical projects in which our Centre is involved. You individually take ownership of the success of the project or product development, despite the difficulties posed e.g. by a context of complex and changing requirements. In such groups you individually lead the collaboration required to solve complex problems. Such groups of work are characterised by a medium to large participation, representing different backgrounds, possibly conflicting interests, points of view and including external collaborators from partner institutions. You coordinate the resources entrusted to you in effective ways, proactively keeping a strong awareness of the overall context of which, your activities are part of, and that you, as senior engineer contributes to shape. You follow-up with clients and local teams to ensure requirements are met; and you lead continuous improvement efforts. You contribute or lead to activities meant to enable and support the business of the Centre  \(e.g. procurement, budgeting, hiring \).", "10"],
	"4": ["You develop and execute mentorship plans for more junior colleagues. Similarly, you engage with colleagues to understand their difficulties at work, and you proactively support them. Within your domains of specialisation, you strive to keep your knowledge up to date, which you proactively share in a structured way. You identify and propose measures to improve the way you and your teams perform the work, for example through new or improved operational procedures, conventions, methods of work, as well as adopting industry established standards.", "10"],
	"5": ["You communicate on complex and sensitive topics, that you might not be familiar with, to a heterogeneous audience representing different backgrounds and conflicting interests. In coordination with your lead, you take the initiative to present internally and externally the vision of the Centre in own field of activity and expertise. Take leadership in the documentation process for a given implementation or solution. You mentor colleagues in the production of posters, papers and other contributions for external events  \(e.g. conferences, workshops \). You moderate to discussions with PIs, researchers, external vendors, and partners.", "10"],
	"6": ["You are responsible to propose, define and deliver trainings, workshops, and similar activities, as outlined by the internal stakeholders \(es. WS lead, Service Managers, Unit Head, others\).", "5"],
	"7": ["You identify needs and propose to your line manager concrete actions to upkeep and expand your skills and capabilities, in line with the current or foreseeable needs. As a result, you might participate to trainings, conferences, workshops, self-study. You share relevant the new knowledge acquired with colleagues in a structured way. You suggest and contribute to similar actions on the organizational level. Thus, you develop a plan for the development of the organization and actively follow its executions. You expand your knowledge of the relevant technologies, vendors, and partner institutions, thus developing a network of key contacts.", "10"]
	}
	}
}

Requirement_base = "Solid theorical and practical knowledge background in the field of activity. Demonstrated strive to keep skills and knowledge up-to-date with industry development, technologies, methods, best practices, frameworks and standards in line with current direction of the Centre. General understanding of HPC environments and scientific computing, fundamental algorithms in science and engineering, and computer architecture, with practical experience. Experience installing and maintaining services in Linux and Kubernetes environments. Effective verbal and written communication skills, with full English proficiency. You are open to take on activities of a different nature, if needed."

Requirement_fl = {
	6: "University degree \(or equivalent practical experience\) in computer science or in a natural science with a high degree of competence in computer science, and with additional relevant technical training.",
	7: "University degree \(or equivalent practical experience\) in computer science or in a natural science with a high degree of competence in computer science, and with additional relevant technical training. At least two years of experience in a relevant professional working environment. Up-to-date knowledge of the technological landscape of the area of activity, as well as vendors roadmaps. Ability to cope with stress and criticism. Ability to lead small teams, even without formal authority.",
	8: "University degree \(or equivalent practical experience\) in computer science or in a natural science with a high degree of competence in computer science, and with additional relevant technical training. At least eight years of experience in a relevant professional working environment. Up-to-date knowledge of the technological landscape of the area of activity, as well as vendors roadmaps. Mentoring capabilities towards more junior colleagues, and ability to cope with stress and criticism. Demonstrated ability to cultivate a network of key contacts with vendors, partners and throughout the community we serve and collaborate with. Ability to lead teams, even without formal authority.",
	9: "University degree, ideally at last at the MSc level \(or equivalent practical experience\) in computer science or in a natural science with a high degree of competence in computer science, and with additional relevant technical training. At least twelve years of experience in a relevant professional working environment. Up-to-date knowledge of the technological landscape of the area of activity, as well as vendors roadmaps. Mentoring capabilities towards more junior colleagues, and ability to cope with stress and criticism. Demonstrated ability to cultivate a network of key contacts with vendors, partners and throughout the community we serve and collaborate with. Ability to lead medium to large teams, even without formal authority.",
	10: "University degree, ideally at the PhD level \(or equivalent practical experience\) in computer science or in a natural science with a high degree of competence in computer science, and with additional relevant technical training. At least fifteen years of experience in a relevant professional working environment. Up-to-date knowledge of the technological landscape of the area of activity, as well as vendors roadmaps. Mentoring capabilities towards more junior colleagues, and ability to cope with stress and criticism. Demonstrated ability to cultivate a network of key contacts with vendors, partners and throughout the community we serve and collaborate with. Ability to lead medium to large teams, even without formal authority."
}
